#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = caelestia-shell
exec-once = hyprshell run &

exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] brave
exec-once = [workspace 3 silent] zeditor
exec-once = [workspace 4 silent] rocketchat-desktop
